package com.example.rdpasswordquality.utils

import android.app.admin.DevicePolicyManager.*


fun passwordQualityConverter(quality: String) = when(quality) {
    "PASSWORD_QUALITY_UNSPECIFIED" -> PASSWORD_QUALITY_UNSPECIFIED
    "PASSWORD_QUALITY_BIOMETRIC_WEAK" -> PASSWORD_QUALITY_BIOMETRIC_WEAK
    "PASSWORD_QUALITY_SOMETHING" -> PASSWORD_QUALITY_SOMETHING
    "PASSWORD_QUALITY_NUMERIC" -> PASSWORD_QUALITY_NUMERIC
    "PASSWORD_QUALITY_NUMERIC_COMPLEX" -> PASSWORD_QUALITY_NUMERIC_COMPLEX
    "PASSWORD_QUALITY_ALPHABETIC" -> PASSWORD_QUALITY_ALPHABETIC
    "PASSWORD_QUALITY_ALPHANUMERIC" -> PASSWORD_QUALITY_ALPHANUMERIC
    "PASSWORD_QUALITY_COMPLEX" -> PASSWORD_QUALITY_COMPLEX
    else -> PASSWORD_QUALITY_UNSPECIFIED
}